version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.0
    steps:
      - checkout
      - run:
          command: terraform init -input=false
      - run:
          command: terraform apply -input=false -auto-approve